v0.8.0 to v0.9.0

diff --git a/src/deb/data/stegosuite b/src/deb/data/stegosuite
--- a/src/deb/data/stegosuite
+++ b/src/deb/data/stegosuite
@@ -1,13 +1,13 @@
-#!/bin/bash
+#!/bin/sh
 
 DIRNAME="/usr/share/stegosuite"
 STEGOSUITEJAR=$(echo $DIRNAME/stegosuite-*.jar)
 
 # Setup the classpath
 if [ ! -f "$STEGOSUITEJAR" ]; then
-    die "Missing required file: $STEGOSUITEJAR"
+    >&2 echo "Missing required file: $STEGOSUITEJAR"; exit 1
 fi
 
 STEGOSUITE_CLASSPATH="$STEGOSUITEJAR"
 
-java -jar $STEGOSUITE_CLASSPATH $@
+java -jar "$STEGOSUITE_CLASSPATH" "$@"
